[workspace]
members = [
	"arch",
	"boot",
	"device/tree",
	"device/uart",
	"firmware",
	"firmware/sbi",
	"firmware/tfa",
	"firmware/uefi",
	"memory",
	"memory/allocator",
	"tool/macro/endian",
	"tool/macro/io",
	"tool/macro/parser",
	"tool/regex",
	"tool/sync",
	"tool/unit",
	"xtask"
]
resolver = "3"
