[package]
name = "boot"
version = "0.1.0"
edition = "2024"
build = "../firmware/build.rs"

[dependencies.arch]
path = "../arch"

[dependencies.firmware]
path = "../firmware"

[dependencies.uart]
path = "../device/uart"

[target.'cfg(target_arch = "riscv64")'.dependencies.tree]
path = "../device/tree"

