[alias]
benv = "run --package xtask -- environment build"
denv = "run --package xtask -- environment delete"
penv = "run --package xtask -- environment privilege"
renv = "run --package xtask -- environment rebuild"
lint = "clippy --workspace --all-targets --all-features -- -D warnings"
