name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v4
      - run: cargo xtask build
      - uses: actions/upload-artifact@v4
        with:
          name: aarch64
          path: target/HomeROS/aarch64
      - uses: actions/upload-artifact@v4
        with:
          name: riscv64
          path: target/HomeROS/riscv64
      - uses: actions/upload-artifact@v4
        with:
          name: x64
          path: target/HomeROS/x64
